paths:
  /inventory:
    get:
      security:
          - Authorization: []
      tags:
        - INVENTORY
      summary: Get list of Inventory.
      parameters:
        - name: search
          in: query
          description: Search will be applied to mac address, model, variant, version, color, distribution.
          schema:
            type: string
            example: Blue      
        - name: version_id
          in: query
          description: To Apply filter based upon model, variant and version.
          required: false
          schema:
            type: string
            example: 1,2
        - name: color
          in: query
          description: To Apply filter based on color.
          required: false
          schema:
            type: string
            example: red
        - name: distribution
          in: query
          description: To Apply filter based distribution.
          required: false
          schema:
            type: string
            example: t'challa PVT LTD
        - name: status
          in: query
          required: false
          schema:
            type: string
            example: ASSIGNED
        - name: distribution_id
          in: query
          description: To get devices assigned to a distribution.
          required: false
          schema:
            type: string
            example: dr_1
        - name: Authorization
          in: headers
          description: Id token to be provided to access.
          schema:
            type: string
        - name: page_number
          in: query
          description: Number of the page to be shown.
          schema:
            type: integer
            example: 1
        - name: page_limit
          in: query
          description: Limit of items to per page.
          schema:
            type: integer
            example: 10
      responses:
        200:
          $ref: "#/components/responses/listInventoryResponse"
        401:
          $ref: "#/components/responses/unauthorizedRequest"
        403:
          $ref: "#/components/responses/forbiddenRequest"
        500:
          $ref: "#/components/responses/internalError"
  /inventory/csv:
    post:
      security:
          - Authorization: []
      tags:
        - INVENTORY
      summary: To add devices using CSV file.
      parameters:
        - name: Authorization
          in: headers
          description: Id token to be provided to access.
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/importCsv"
      responses:
        200:
          $ref: "#/components/responses/importCsvSuccess"
        400:
          $ref: "#/components/responses/csvSomethingWentWrong"
        401:
          $ref: "#/components/responses/unauthorizedRequest"
        403:
          $ref: "#/components/responses/forbiddenRequest"
        500:
          $ref: "#/components/responses/internalError"
  /inventory/csv-history:
    get:
      security:
          - Authorization: []
      tags:
        - INVENTORY
      summary: List the CSV import history.
      parameters:
        - name: Authorization
          in: headers
          description: Id token to be provided to access.
          schema:
            type: string
        - name: page_limit
          in: query
          schema:
            type: string
            example: 2
        - name: page_number
          in: query
          schema:
            type: string
            example: 10
      responses:
        200:
          $ref: "#/components/responses/importCsvHistory"
        401:
          $ref: "#/components/responses/unauthorizedRequest"
        403:
          $ref: "#/components/responses/forbiddenRequest"
        500:
          $ref: "#/components/responses/internalError"
