exports.dbTables = {
  ROLES_TABLE: 'aergov_roles',
  USER_ROLES_TABLE: 'aergov_user_roles',
};

exports.successResponses = {
  TOKEN_DATA_FETCHED: `Token data fetched successfully`,
};

exports.errorResponses = {
  SOMETHING_WENT_WRONG: `Something went wrong`,
  ACCESS_DENIED: `Access denied`,
  INVALID_CSV_FILE: `Invalid csv file`,
};

exports.permissions = {
  VIEW_LIST_INVENTORY: `INVENTORY#INVENTORY_TAB#TAB_LIST_VIEW`,
  ASSIGN_DEVICES: `DISTRIBUTIONS#DISTRIBUTIONS_TAB#ASSIGN_DEVICES`,
  UNASSIGN_DEVICES: `DISTRIBUTIONS#DISTRIBUTIONS_TAB#UNASSIGN_DEVICES`,
  CSV_IMPORT_HISTORY: `INVENTORY#INVENTORY_TAB#IMPORT_HISTORY`,
  IMPORT_CSV: `INVENTORY#INVENTORY_TAB#IMPORT_CSV`,
  SAMPLE: `SAMPLE`,
  ADD_ROLE: `USERS#ROLES_TAB#ADD_ROLE`,
  LIST_ROLES: `USERS#ROLES_TAB#TAB_LIST_VIEW`,
  ADD_USER: `USERS#USERS_TAB#ADD_USER`,
  LIST_USER: `USERS#USERS_TAB#TAB_LIST_VIEW`,
  EDIT_USER: `USERS#USERS_TAB#EDIT_USER`,
  ADD_DISTRIBUTION: `DISTRIBUTIONS#DISTRIBUTIONS_TAB#ADD_DISTRIBUTION`,
  EDIT_DISTRIBUTION: `DISTRIBUTIONS#DISTRIBUTIONS_TAB#EDIT_DISTRIBUTION`,
  LIST_DISTRIBUTIONS: `DISTRIBUTIONS#DISTRIBUTIONS_TAB#TAB_LIST_VIEW`,
};

exports.tokenTypes = {
  ID_TOKEN: `ID_TOKEN`,
  REFRESH_TOKEN: `REFRESH_TOKEN`,
};

exports.methods = {
  POST: `POST`,
  GET: `GET`,
  PATCH: `PATCH`,
  PUT: `PUT`,
  DELETE: `DELETE`,
};
